### ISSUE TITLE
closed_categories.json file missing.

### ISSUE THREAD

**Issue by zippeurfou** [Wenyueh/LLM-RecSys-ID#1]
Thanks for this great repository @Wenyueh and @evison.
I was trying to understand how some of the yelp part of the code works and I think some data are missing.
More specifically:
`closed_categories.json` from
https://github.com/Wenyueh/LLMforRS_item_representation/blob/18f638a242798db10dff2a5a3607308154998676/item_rep_method.py#L273-L276
As you can see in this screenshot from the readme download [link](https://drive.google.com/u/0/uc?id=1qGxgmx7G_WB7JE4Cn_bEcZ_o_NAJLE3G&export=download): 
<img width="316" alt="Screenshot 2023-08-24 at 2 30 58 PM" src="https://github.com/Wenyueh/LLMforRS_item_representation/assets/4520383/900cc41d-a3a3-4843-b6bd-2f2793910d88">
The data seems to not be there.
It is possible this is because this was "closed"/"private" data that you were not able to share publicly.
If so, I'd recommend to add this into the readme or the code as a comment so this help future reader.

**Comment by Wenyueh** [comment]
Hello Marc,

Thank you for your interest in the project. The data is under /data/yelp/ in the repository

**Comment by zippeurfou** [comment]
ahah ok my bad :)
Will close this.

**Comment by zippeurfou** [comment]
@Wenyueh If I may ask, how did you create this file?

**Comment by Wenyueh** [comment]
The file is created based on frequency counting of tags in Yelp and a hierarchical structure is of categories built based on the frequency counting. Basically the idea is: the most frequently occurred tags will be highest level of category; categories below them are selected based on co-occurrences counting. The code is not very organized yet and I will upload them when I cleaned them up.

**Comment by zippeurfou** [comment]
Thanks @Wenyueh can't wait to see the code :)

**Comment by zippeurfou** [comment]
Sorry to keep messaging on this closed issue. 
I keep wondering if this method introduces temporal leakage. 
CID might be more affected by it. 
The naive idea is that if you use co occurrence to generate your CID or SemID then you're using data you're going to train on before training on them potentially creating an unfair advantage versus when you compare it to other methods. 
Does it make sense @Wenyueh ?

**Comment by Wenyueh** [comment]
Hi, 

No worries and thank you for asking questions :)

The indices for CID are generated only using co-occurrences from the training dataset; thus no leaking for validation and test.

As for the indices for SemID, the co-occurrences I meant in the previous message was referring to the co-occurrences of tags, not items. Thus will not be a leakage and all methods have access to that :)

Hope it's clear!

**Comment by zippeurfou** [comment]
Thanks for the answer that makes total  sense.
