### ISSUE TITLE
为什么大部分结果都不如P5？你是训练了20个epoch吗？会不会太少了？

### ISSUE THREAD

**Issue by zhaijianyang** [Wenyueh/LLM-RecSys-ID#3]

**Comment by Wenyueh** [comment]
好问题，因为P5本身的indexing其实是有问题的(have some sort of data leakage)，才导致它结果很高。我们用p5原先的indexing做实验基本上hit@10能到8 - 10。

**Comment by evison** [comment]
We appreciate your interest in this work. We think most of the advanced indexing methods are actually giving better results than P5. First, the three naive indexing methods (RID, TID, IID) are purposely used to show that trivial indexing does not work, so it's not surprising that their performance is worse than P5, actually, that's what our paper wanted to show. However, for the advanced indexing methods (SID, CID, SemID and their combinations), most of them are comparable or better than P5. Of course, they may not always be better. We see on some datasets P5 is better while on others this work is better. There could be many factors contributing to this difference, but one important factor we think is that P5 is jointly trained on multiple tasks (five tasks actually), while this work is only trained on one task (sequential task). This means that the pre-training data and tasks are significantly different between the two, e.g., P5 uses a lot of textual information such as user reviews, which is not used in this work. As a result, though the two works are both better than baselines, it might not be directly applicable to compare these two works, considering their different pre-training data and tasks.
