### ISSUE TITLE
The large gap compared to P5

### ISSUE THREAD

**Issue by woriazzc** [Wenyueh/LLM-RecSys-ID#4]
Hi! It's a great work!
However, according to your experimental results, I find that the performance is much worse than P5, especially on Yelp. Since I'm trying to reproduce and compare the various LLM+RS methods, I'd like to ask what is causing this problem.

I have seen that another issue also proposed this problem, but the gap is especially huge on Yelp, even for hybrid indexing methods. So I guess maybe there are other reasons, such as the design choices or implementations?

**Comment by evison** [comment]
We appreciate your interest in this work and your insightful discussions. We see on some datasets P5 is better while on others this work is better. There could be many factors contributing to this difference, but one important factor we think is that P5 is jointly trained on multiple tasks (five tasks actually), while this work is only trained on one task (sequential task). This means that the pre-training data and tasks are significantly different between the two, e.g., P5 uses a lot of textual information such as user reviews, which is not used in this work. As a result, though the two works are both better than baselines, it might not be directly applicable to compare these two works, considering their different pre-training data and tasks.
