### ISSUE TITLE
关于负样本数量

### ISSUE THREAD

**Issue by zhaijianyang** [Wenyueh/LLM-RecSys-ID#5]
你好，关于负样本我有一点疑问：
1. 对于SASRec等baseline方法，有些文章中随机选取一个负样本，有些是把除了正样本的所有item作为负样本（比如RecBole中的交叉熵损失），它们对性能的影响还是比较大的。
2. P5虽然没有选取负样本，但是在IID的时候，每个物品有一个embedding，最后的交叉熵损失仍然是把除了正样本的所有item作为负样本，所以P5和baseline的比较是否有些不公平？

**Comment by Wenyueh** [comment]
Hello, thank you for your question.
我个人觉得很难比较，这篇文章提供的方法都是generative recommendation的方法，本质上是llm的next token generation，跟用正负样本contrastive loss来训练和学习的模型很难直接比较。

因为本文提供的方法都属于generative recommendation，所以在IID的时候，不仅仅是所有其它item的embedding是负样本，vocabulary里面其它30k+的无关token也同样作为负样本出现。从样本正负的角度来看，这些是否可以看做是noise？对模型也可能有负面作用？所以从样本角度来看，IID的方法也同样不是optimal的。如果要跟你所说的把其它所有物品作为负样本的类似sasrec的baseline来比较的话，那也同样应该引入30k+的其它noisy的“负样本”。

欢迎讨论

**Comment by zhaijianyang** [comment]
感谢回复，
那是不是可以考虑去掉这些“负样本”做一个公平的比较，比如修改最后的分类头，只输出IID。因为最后也不需要输出文字token。这样的话，本质上和SASrec的seq2one是不是有点类似？

**Comment by Wenyueh** [comment]
train的时候在某些step把vocab的一部分mask掉是可以的（因为我们其实生成的是item_ID而不是单纯的ID），inference的时候因为我们本来也用了constraint的beam search 所以不需要考虑

**Comment by zhaijianyang** [comment]
感谢回复，
那是不是可以考虑去掉这些“负样本”做一个公平的比较，比如修改最后的分类头，只输出IID。因为最后也不需要输出文字token。这样的话，本质上和SASrec的seq2one是不是有点类似？
或者说这是generative retrieval的一个固有缺点，用LLM其效果并没有本质上超过传统方法（大量负样本的方法）？

**Comment by evison** [comment]
我个人觉得LLM-based generative recommendation和“大量负样本采样”这两者之间并不是竞争的关系，而是互补的关系；具体而言，可以把大量负样本采样这件事情加到LLM的pre-training或fine-tuning上，可能可以进一步提升效果；有很多不同的方式可以实现这件事情，比如1）可以分别构建positive prompt和negative prompt（P5的sequential recommendation task本质上只包含positive prompt），然后让两种prompt同时参与pre-training，2）也可以把LLM经典的predict next word loss变成一种contrastive loss，类似于BPR loss，也就是显式地让正样本的score大于负样本的score，这样就可以在LLM pre-training或fine-tuning过程中进行大量的负采样，并加入到模型的训练中，这些都是值得探索的方向。

**Comment by Wenyueh** [comment]
同意。而且用generative recommendation的方法，核心也不是IID这样每个item一个embedding的做法，而是每个item用多个token表示，让billions of items都可以用一个同一个limited vocabulary表示。在这种情况下optimal的正负样本做法很可能是不scalable的，但是对generative recommendation来说就不是问题。

**Comment by zhaijianyang** [comment]
明白了，谢谢各位大佬回复~

**Comment by Wenyueh** [comment]
不谢
